### ISSUE TITLE
Automatically Adding Jumps in Crossing wires

### ISSUE THREAD

**Issue by bolasim** [KenKundert/svg_schematic#1]
What you would recommend for adding this quickly? I'm happy to do it then send a PR.

**Comment by KenKundert** [comment]
Sorry, I did not see this issue earlier. I do not know how to do what you are suggesting in an automatic fashion. However it is not difficult to add cross-overs manually. Just add a dot (Dot) at the intersection of the two wires and make it white. You just have to make sure the dot is specified after the top wire and before the bottom wire. 
`Dot((x, y), color='white')`
