### ISSUE TITLE
Documentation: Bad Request (400)

### ISSUE THREAD

**Issue by jshlian** [KenKundert/svg_schematic#2]
Documentation seems to be pointing to the wrong link. Google search yields documentation at https://svg-schematic.readthedocs.io/en/latest/ - is this correct?

Thanks!

**Comment by KenKundert** [comment]
Thanks.  Should be fixed now.

**Comment by jshlian** [comment]
Fixed in the PyPI link, still broken in the header. Seems to be line 8. Sorry to be nitpicky.

**Comment by KenKundert** [comment]
No worries.  I appreciate your attention to details.  I think I have got them all now.  Thanks!
